<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuite3_Script</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e9035f62-7493-4691-b46c-4baa6ab2b92e</testSuiteGuid>
   <testCaseLink>
      <guid>4723df49-a604-457a-9ea9-bf3729371465</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase3_Script_Excel</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f451730b-a74d-4295-abcf-50ebca71e9bf</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData1</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b89c436b-f59b-48ef-8fba-5974b52a88d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fc08847-d4ec-4ebd-b748-b5a3a5c5cda7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
